# Generated by Django 3.1.4 on 2021-01-29 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nametext', models.CharField(max_length=10)),
                ('birdate', models.DateField(null=True)),
                ('zwtext', models.CharField(max_length=10)),
                ('zwdate', models.DateField(null=True)),
                ('djtext', models.CharField(max_length=10)),
                ('djdate', models.DateField(null=True)),
                ('zctext', models.CharField(max_length=10)),
                ('zcdate', models.DateField(null=True)),
                ('dwtext', models.CharField(max_length=40)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
