# Generated by Django 3.1.4 on 2021-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='djdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zcdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zwdate',
            field=models.DateTimeField(null=True),
        ),
    ]
