# Generated by Django 3.1.4 on 2021-01-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210129_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='djdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zcdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zwdate',
            field=models.DateField(null=True),
        ),
    ]
