# Generated by Django 3.1.4 on 2021-02-13 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210129_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ryimage',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='ryimage'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
