# Generated by Django 3.1.4 on 2021-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_publish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
