# Generated by Django 3.1.4 on 2021-02-15 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210205_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entryimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='entryimg/', verbose_name='entryimage')),
                ('enry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry')),
            ],
        ),
    ]
