# Generated by Django 3.1.6 on 2021-02-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_entryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryimage',
            old_name='enry',
            new_name='entry',
        ),
    ]
