# Generated by Django 3.1.6 on 2021-02-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210217_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entryimage',
            old_name='entry',
            new_name='entry_image',
        ),
    ]
